name:                overeasy
version:             0.1.0
github:              "ejconlon/overeasy"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2021 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/overeasy#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs >= 0.5 && < 0.7
- containers >= 0.6 && < 0.7
- deepseq >= 1.4 && < 1.5
- hashable >= 1.3 && < 1.5
- int-like >= 0.1 && < 0.2
- mtl >= 2.2 && < 2.3
- recursion-schemes >= 5.2 && < 5.3
- text >= 1.2 && < 2.1
- transformers >= 0.5 && < 0.7
- unordered-containers >= 0.2 && < 0.3

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- PatternSynonyms
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

tests:
  overeasy-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - overeasy
    - hedgehog
    - pretty-simple
    - tasty
    - tasty-hedgehog
